engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
          mass_threshold: 20
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
